warning: Debugger speedups using cython not found. Run '"/Users/XiangyuW/anaconda3/bin/python3.6" "/Users/XiangyuW/.p2/pool/plugins/org.python.pydev.core_6.3.3.201805051638/pysrc/setup_cython.py" build_ext --inplace' to build.
pydev debugger: starting (pid: 1013)
/Users/XiangyuW/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Successfully load data from pickle /Users/XiangyuW/Google Drive/Research2015/ReweightMF/Code/Python/testdata/input_datasets/YaleFace1.pickle!
Data loaded successfully from /Users/XiangyuW/Google Drive/Research2015/ReweightMF/Code/Python/testdata/input_datasets/YaleFace1.pickle !

***********Begins test no.  1
The projected low rank is  144
The initial randon shuffle is  [125  86  18  92 108  29 102  72  39 118 130  55  10  45  12 121  47  24
  73  35 146   6 122  41 110  13 128 155  87 135  25 117  77 126  49  93
  94 114  83 154  68 113 101  76  46  85  30 151  53  50  65  20  56  23
  74  28  16   7  71  88  38  42 139 143 103  99 112   2  98  17  67   0
  33 150 124  70   9  22 148  90 136  78 100 145  32   8   1  62  36   3
 147 132  96  57 134 142  89  59 133 109 111  82  34  11  27  26  61 105
  91 149  44 107  97  51 106  21  37 123 120  31  69 138 140  75  60 104
  40  63 153  52 144  14 141 119   4  19 129  58 116   5 137  15  66  81
  84 131 115  95 152  54  80  64 127  43  48  79]
********
Starting the AGD-type ALM FGD---Accelerate Basis********

The initial err is  29035.725469706715

The 1-th iteration of Accelerated ALM FGD
Traceback (most recent call last):
  File "/Users/XiangyuW/.p2/pool/plugins/org.python.pydev.core_6.3.3.201805051638/pysrc/pydevd.py", line 1655, in <module>
    main()
  File "/Users/XiangyuW/.p2/pool/plugins/org.python.pydev.core_6.3.3.201805051638/pysrc/pydevd.py", line 1649, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Users/XiangyuW/.p2/pool/plugins/org.python.pydev.core_6.3.3.201805051638/pysrc/pydevd.py", line 1055, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/XiangyuW/.p2/pool/plugins/org.python.pydev.core_6.3.3.201805051638/pysrc/_pydev_imps/_pydev_execfile.py", line 25, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/XiangyuW/Google Drive/Research2015/ReweightMF/Code/Python/test_RWLR_rank_effect.py", line 147, in <module>
    U1,g1,err_list1,g_list1 = test_model_theta.apply_RW_AGD_NC(w_kernel, par_kernel,U_update_method,n_inner_loop,oscillation_control = 3)
  File "/Users/XiangyuW/Google Drive/Research2015/ReweightMF/Code/Python/RWLR_support.py", line 1387, in apply_RW_AGD_NC
    err_pre = record_error(err_pre,err_t,iter_t+1,oscillation_control,self.delta_err_min,err_list,g_list)
TypeError: record_error() missing 1 required positional argument: 'g_list'
