warning: Debugger speedups using cython not found. Run '"/Users/XiangyuW/anaconda3/bin/python3.6" "/Users/XiangyuW/.p2/pool/plugins/org.python.pydev.core_6.3.2.201803171248/pysrc/setup_cython.py" build_ext --inplace' to build.
pydev debugger: starting (pid: 1739)
/Users/XiangyuW/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Err in loading pickle files and the infor is:  invalid literal for int() with base 10: 'AB 5.0 MAT-file, Platform: MACI64, Created on: Wed Feb 22 18:11:32 2017                                         '


We now try loding data from mat /Users/XiangyuW/Google Drive/Research2015/SNMF_clustering/SNMFUKmeans/Code/facedata/face_19x19.mat!


Successfully load data from mat /Users/XiangyuW/Google Drive/Research2015/SNMF_clustering/SNMFUKmeans/Code/facedata/face_19x19.mat!
Data loaded successfully from /Users/XiangyuW/Google Drive/Research2015/SNMF_clustering/SNMFUKmeans/Code/facedata/face_19x19.mat !
Backend MacOSX is interactive backend. Turning interactive mode on.
Python 3.6.3 |Anaconda, Inc.| (default, Oct  6 2017, 12:04:38) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.
PyDev console: using IPython 6.1.0
(165, 15)

The error infor is  index 15 is out of bounds for axis 1 with size 15

 Saving as mat file.
data is saved in /Users/XiangyuW/Google Drive/Research2015/ReweightMF/Code/Python/testdata/YaleFace1.mat.

 Saving as pickle file.
data is saved in /Users/XiangyuW/Google Drive/Research2015/ReweightMF/Code/Python/testdata/YaleFace1.pickle.
